# Generated by Django 4.1.7 on 2023-06-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationslot',
            old_name='center',
            new_name='center_1',
        ),
    ]
