# Generated by Django 4.1.7 on 2023-06-02 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_center_vaccinationslot_center_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationslot',
            name='center_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vaccinationcenter'),
        ),
    ]
